### ISSUE TITLE
multi-part form 

### ISSUE THREAD

**Issue by nimi96** [viane/microsoft-computer-vision#3]
Thank you so much for providing such help. any updates for multi-part update ?

**Comment by viane** [comment]
Hi there, thank you for the comment, i was really busy recently doing school work, and I will be working on this implementation as soon as next week starts. Please feel free to add more if you want me to add to the package.

**Comment by viane** [comment]
Hello again, sorry for the delay, I was finally able to get free time on this, and right now the multipart functionality is added to the package so as the new option for selecting API location. Please check the [new doc here](https://github.com/viane/microsoft-computer-vision/blob/master/README.md) 

And thanks for the support and usage mate!

**Comment by nimi96** [comment]
Thank you so much dude .you are life saviour. you own me one.  warm regards,
Nimit pamnani
phone no:8826156493
 
 

    On Friday, 14 July 2017 5:46 PM, xiaoyu zhou <notifications@github.com> wrote:
 

 Hello again, sorry for the delay, I was finally able to get free time on this, and right now the multipart functionality is added to the package so as the new option for selecting API location. Please check the new doc hereAnd thanks for the support and usage mate!—
