### ISSUE TITLE
Always getting invalid subscription error

### ISSUE THREAD

**Issue by hardikchoudhary** [viane/microsoft-computer-vision#4]
Hi @viane  @codacy-badger 

Please help me in this regard thankss

I am getting error when i am using this...unable to use computer vision
const microsofComputerVision = require("microsoft-computer-vision");
microsofComputerVision.orcImage({
    "Ocp-Apim-Subscription-Key": "Keep this safe :D",
    "request-origin":"westus",
    "content-type": "application/json",
    "url": "http://cdn.quotesgram.com/img/81/49/660235022-Random-Funny-Quotes-.jpg",
    "language": "en",
    "detect-orientation": true
}).then((result)=>{
 
  console.log(JSON.stringify(result));        // { 
                              //     "language": "en", 
                              //     "textAngle": 0, 
                              //     "orientation": "Up", 
                              //     "regions": [ 
                              //         { 
                              //             "boundingBox": "7,55,605,387", 
                              //             "lines": [ 
                              //                 { 
                              //                     "boundingBox": "7,55,603,65", 
                              //                     "words": [ 
                              //                         { 
                              //                             "boundingBox": "7,59,291,61", 
                              //                             "text": "HOME:" 
                              //                         }, 
                              //                         { 
                              //                             "boundingBox": "326,55,284,65", 
                              //                             "text": "Where" 
                              //                         } 
                              //                     ] 
                              //                 }, 
                              //                 ... 
                              //             ] 
                              //         } 
                              //     ] 
                              // } 
}).catch((err)=>{
  throw err;
});

**Comment by viane** [comment]
Hi Mate, thanks for the comment, I have test by your subscription key.
Turns out that the only valid origin for you key is  `westcentralus`. I not familiar with how MS assign which region corresponding to which key or why one region binds to each key only. I'm assuming the region is based on the information when you create the account. Like mine only works for `westus`, but I'm living in east coast :P 
In this case, I wouldn't worry a lot since when I try use west region API, the response is less than 2s avg, so I think you will be fine. Feel free to talk to MS and let me know the updates, I'd happy to change to request-region function more easy to use.

**Comment by hardikchoudhary** [comment]
Thanks for the reply mate. Even i have tried with westcenteralus with this subscription key e825f9b7fdf04fc5ac1544c35598f1c6 i will update it once it get resolved 

can you please help what i can do 

what are the steps i can do

i go to the computer vision api and had a key with me 

Please help me again 

Thanks  alot

**Comment by hardikchoudhary** [comment]
@viane  where i can find this Ocp-Apim-Subscription-Key 

is this the same key that is given when we click on get Api for computer vision or its somewhere else

Thanks

**Comment by viane** [comment]
Hi, there, so base on what I know and tried is the following:
2b4043ad15ef443eb4b25182c6ac9dab this key can work in the `westcentralus` region,
e825f9b7fdf04fc5ac1544c35598f1c6 this key has different format (length), I believe this one supposed to be used in different APIs.
You can test your key at this [page](https://westeurope.dev.cognitive.microsoft.com/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fc), this is official MS computer vision API page.
Would you mind tell me how did you get the second key?

**Comment by hardikchoudhary** [comment]
Thank you so much for the help , second key was with my other gmail account. May be it was from diff. region other then westcentral us and 2b key works....thanks alottt :) :)
:)
can you give me some scenarios for the bot i can work on and please update the key from the comments 📦 
thanks again @viane
